# Generated by Django 5.2.4 on 2025-09-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0009_book_publication_date_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_manage_books', 'Can add, edit, or delete books'),)},
        ),
    ]
