from django.urls import include, path
from rest_framework.routers import DefaultRouter
from . import views

# Create a router instance
router = DefaultRouter()

# Register our ViewSets with the router.
# The first argument is the URL prefix (e.g., 'books').
# The second argument is the ViewSet class.
router.register(r'books', views.BookViewSet)
router.register(r'authors', views.AuthorViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # The `include` function includes all the URLs generated by the router.
    # The router automatically creates a root view at the empty path ''.
    path('', include(router.urls)),
]
